version: '3.8'

services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: overwatch-2-companion-api
    volumes:
      - ./storage:/var/www/overwatch-2-companion-api/storage
      - ./public:/var/www/overwatch-2-companion-api/public
      - /var/www/overwatch-2-companion-api/.env:/var/www/overwatch-2-companion-api/.env
    ports:
      - "8080:9000"
    networks:
      - app_network
    depends_on:
      - mysql
      - redis
      - meilisearch

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  meilisearch:
    image: getmeili/meilisearch:latest
    volumes:
      - meilisearch_data:/data.ms
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  meilisearch_data:
