name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        echo "VPS_USER: ${{ secrets.VPS_USER }} characters"
        echo "VPS_HOST: ${{ secrets.VPS_HOST }} characters"
        echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} characters"

      # run: ssh -o "StrictHostKeyChecking=no" ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'bash -s' < ~/scripts/deploy.sh
